name: CI Self-hosted

on:
  workflow_dispatch:

jobs:
  run-visualization-local:
    runs-on: [self-hosted, Windows, X64]
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: ./_actions/actions/checkout/v4

      - name: Use system Python
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org
          pip install pandas matplotlib openpyxl xlrd --trusted-host pypi.org --trusted-host files.pythonhosted.org

      - name: Run visualization module
        shell: cmd
        run: |
          pip show pandas xlrd
          python src\visualization.py

      - name: Upload artifacts
        uses: ./_actions/actions/upload-artifact/v4
        with:
          name: artifacts-visualization-selfhosted
          path: artifacts\visualization